language: node_js
node_js:
  - "7"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install
  - ng build
script:
  - ng test --watch false